name: Sync from Algolia index

permissions:
  contents: write
  pages: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: actions-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run fetcher script
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_BASE_URL: ${{ vars.ALGOLIA_BASE_URL }}
          ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }}
        run: deno run --allow-net --allow-read --allow-write --allow-env fetcher.ts

      - name: Format README.md
        run: deno fmt README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m ":card_file_box: Synced data: $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
